app.frontend.base-url=${WEB_BASE_URL:https://api.sheriaconnect.co.tz}
app.frontend.base-domain=${WEB_BASE_DOMAIN:https://sheriaconnect.co.tz}
app.mobile.base-url=sheria://app
app.evidence.storage-root=${EVIDENCE_STORAGE_ROOT:/app/uploads/evidence}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://sheriaconnect.co.tz,https://www.sheriaconnect.co.tz}

