app.frontend.base-url=${WEB_BASE_URL:https://api.sheriaconnect.co.tz}
app.frontend.base-domain=${WEB_BASE_DOMAIN:https://sheriaconnect.co.tz}
app.mobile.base-url=sheria://app
app.evidence.storage-root=${EVIDENCE_STORAGE_ROOT:/app/uploads/evidence}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://sheriaconnect.co.tz,https://www.sheriaconnect.co.tz,https://admin.sheriaconnect.co.tz,https://app.sheriaconnect.co.tz}
app.incident-report.tracking-token-derivation-key=${TRACKING_TOKEN_DERIVATION_KEY}
app.auth.mfa.encryption-key=${MFA_ENCRYPTION_KEY}
app.frontend.auth-base-url=${AUTH_WEB_BASE_URL:https://admin.sheriaconnect.co.tz}
app.frontend.admin-base-url=${ADMIN_BASE_URL:https://admin.sheriaconnect.co.tz}
app.auth.refresh-cookie.secure=${REFRESH_COOKIE_SECURE:true}
spring.jpa.show-sql=false
logging.level.org.springframework.security=INFO

